[bell]
command = "None"
duration = 0

[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.cursor]
cursor = "#ff8c00"
text = "CellBackground"

[colors.normal]
black = "#1d1f21"
blue = "#6f8fb4"
cyan = "#88c0d0"
green = "#93b379"
magenta = "#a4799d"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#e5c179"

[colors.primary]
background = "#0d1117"
foreground = "#cfd6e4"

[colors.search.focused_match]
background = "#000000"
foreground = "#ffff00"

# [colors.search.footer_bar]
# background = "#c5c8c6"
# foreground = "#1d1f21"

[colors.search.matches]
background = "#ffff00"
foreground = "#000000"

[colors.selection]
background = "#4c566a"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[env]
TERM = "alacritty"

[font]
size = 10.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "Hack"
style = "Regular"

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Left", mods = "Command", action = "Open" },
]

[scrolling]
history = 0

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_title = true
startup_mode = "Maximized"

[general]
live_config_reload = true
import = [
  "~/.alacritty_terminal.toml"
]
